# Generated by Django 4.1.1 on 2022-09-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
