# Generated by Django 4.1.1 on 2022-10-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_stocks_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocks',
            name='action',
            field=models.CharField(default='Buy', max_length=10),
            preserve_default=False,
        ),
    ]
